# AI > Data > Encoding

## Description
```
Number  : 1
Type    : Categorical
Model   : Ordinal
Dataset : housesInfo
```

## Import

In [ ]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

## Data

In [39]:
data = asarray([['red'], ['green'], ['blue'], ['purple'], ['black'], ['red']])
print(data)

[['red']
 ['green']
 ['blue']
 ['purple']
 ['black']
 ['red']]


## Encoding

### Integer Encoding

In [40]:
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
print(result)

[[4.]
 [2.]
 [1.]
 [3.]
 [0.]
 [4.]]


### One Hot Encoding

In [41]:
encoder = OneHotEncoder(sparse_output=False)
result = encoder.fit_transform(data)
print(result)

[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]
