# Description
```
Name    : filter_2
Problem : Filter
Dataset : Array
```

# General

### Import

In [5]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from keras import layers, models

### Variable

In [20]:
root_dir = '/Volumes/data/documents/ai_document'

# Action

### Input

In [14]:
x = np.array(
    [
        [3, 5, 2, 7],
        [4, 1, 3, 8],
        [6, 3, 8, 2],
        [9, 6, 1, 5]
    ]
)

x = x.reshape(1, 4, 4, 1)

### weights

In [21]:
weights = [
    np.array(
        [
            [
                [
                    [1]
                ],
                [
                    [2]
                ],
                [
                    [1]
                ]
            ],
            [
                [
                    [2]
                ],
                [
                    [1]
                ],
                [
                    [2]
                ]
            ],
            [
                [
                    [1]
                ],
                [
                    [1]
                ],
                [
                    [2]
                ]
            ]
        ]
    ),
    np.asarray([0])
]

### Decrease : Conv2D

In [58]:
mdl = models.Sequential()
mdl.add(layers.Input(shape=(4, 4, 1)))
mdl.add(layers.Conv2D(1, (3, 3), strides=(1,1), padding="valid"))
mdl.set_weights(weights)
out_1 = mdl.predict(x)
print(x.reshape(4,4))
print("\n")
print(out_1.reshape(2,2))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[3 5 2 7]
 [4 1 3 8]
 [6 3 8 2]
 [9 6 1 5]]


[[55. 52.]
 [57. 50.]]


### Increase : Conv2DTranspose

In [59]:
mdl = models.Sequential()
mdl.add(layers.Input(shape=(2, 2, 1)))
mdl.add(layers.Conv2DTranspose(1, (3, 3), strides=(1,1), padding="valid"))
mdl.set_weights(weights)
out_2 = mdl.predict(out_1)
print(x.reshape(4,4))
print("\n")
print(out_2.reshape(4 ,4))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[3 5 2 7]
 [4 1 3 8]
 [6 3 8 2]
 [9 6 1 5]]


[[ 55. 162. 159.  52.]
 [167. 323. 319. 154.]
 [169. 264. 326. 204.]
 [ 57. 107. 164. 100.]]
